//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CardGame
{
	public class CardObject : MonoBehaviour
	{
		protected Card m_card = new Card();
		protected Vector2 m_position = new Vector2 (0, 0);
		protected GameObject m_obj;

		public Card cardReference { get { return m_card; } set { m_card = value; } }

		public Vector2 Position 
		{ 
			get { return m_position; }
			set 
			{ 
				m_position = value;
				gameObject.GetComponent<Transform>().position = m_position;
			}
		}

		public Card.eSuit Suit {  
			get { return m_card.Suit; }
			set {
				m_card.Suit = value;
				SetTexture();
			}
			
		}
		public Card.eValue Value	
		{ 
			get { return m_card.Value; }
			set {
				m_card.Value = value;
				SetTexture();
			}
		}

		public GameObject gameObject { get { return m_obj; } set { m_obj = value; } }

		public CardObject ()
		{

		}

		void Start()
		{
			//			Renderer rend = gameObject.GetComponent<Renderer>();
			//			rend.material.SetTexture("_MainTex", (Texture)Resources.Load ("king_of_spades"));
		}
		
		protected string SetTexture() {
			
			string texture_name = "";
			string svalue = "";
			string ssuit = "";
			m_card.name = "";
			
			switch (m_card.Value) {
			case Card.eValue.kAce:
				svalue += "ace";
				break;
			case Card.eValue.kTwo:
				svalue += "2";
				break;
			case Card.eValue.kThree:
				svalue += "3";
				break;
			case Card.eValue.kFour:
				svalue += "4";
				break;
			case Card.eValue.kFive:
				svalue += "5";
				break;
			case Card.eValue.kSix:
				svalue += "6";
				break;
			case Card.eValue.kSeven:
				svalue += "7";
				break;
			case Card.eValue.kEight:
				svalue += "8";
				break;
			case Card.eValue.kNine:
				svalue += "9";
				break;
			case Card.eValue.kTen:
				svalue += "10";
				break;
			case Card.eValue.kJack:
				svalue += "jack";
				break;
			case Card.eValue.kQueen:
				svalue += "queen";
				break;
			case Card.eValue.kKing:
				svalue += "king";
				break;
			default:
				return "";
			}
			
			switch (m_card.Suit) {
			case Card.eSuit.kSpades:
				ssuit += "spades";
				break;
			case Card.eSuit.kHearts:
				ssuit += "hearts";
				break;
			case Card.eSuit.kDiamonds:
				ssuit += "diamonds";
				break;
			case Card.eSuit.kClubs:
				ssuit += "clubs";
				break;
			default:
				return "";
			}
			
			m_card.name = svalue + " of " + ssuit;
			texture_name = svalue + "_of_" + ssuit;
			
			Renderer rend = gameObject.GetComponent<Renderer>();
			rend.material.SetTexture("_MainTex", (Texture)Resources.Load (texture_name));
			return texture_name;
		}

		
		public void SetSuitValue(Card.eSuit suit, Card.eValue val)
		{
			m_card.Suit = suit;
			m_card.Value = val;
			SetTexture();
		}

	}
}

