//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Displays the contents of player's hands
/// </summary>
namespace CardGame
{
	public class PlayerHandObject : MonoBehaviour
	{
		protected PlayerHand m_Hand = new PlayerHand();
		protected List<CardObject> m_CardObjects;
		protected CardObject m_currSelCard = null; // the current card in selection

		public PlayerHand playerhand { get { return m_Hand; } set { m_Hand = value; } }
		//public List<CardObject> cardobjects { get { return m_CardObjects; } set { m_CardObjects = value; } }

		public PlayerHandObject ()
		{

		}

		public void Update()
		{

		}

		/// <summary>
		/// Creates the card object in the player hand as a view-representation
		/// </summary>
		/// <param name="card">Card.</param>
		public void CreateCardObj(Card card)
		{
			m_CardObjects.Add(gameObject.AddComponent<CardObject>());
			m_CardObjects[m_CardObjects.Count-1].gameObject = (GameObject)(Instantiate(Resources.Load<GameObject>("Card")));
			m_CardObjects[m_CardObjects.Count-1].gameObject.AddComponent<CardObject>();
			m_CardObjects[m_CardObjects.Count-1].cardReference = card;
			
			m_CardObjects[m_CardObjects.Count-1].SetSuitAndValue( card.Suit, card.Value );
		}

		/// <summary>
		/// Not sure this will work as intended. 
		/// </summary>
		/// <param name="cardObj">Card object.</param>
		public void AddCardObj(CardObject cardObj)
		{
			m_CardObjects.Add(gameObject.AddComponent<CardObject>());
			m_CardObjects[m_CardObjects.Count-1] = cardObj;
		}
	}
}

