//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;

namespace CardGame
{
	public class Player
	{
		public enum ePlayerType { kNone = -1, kHuman = 0, kCPU = 1 };
		protected PlayerHand m_hand = new PlayerHand();
		protected ePlayerType m_playerType = ePlayerType.kNone;
		protected bool m_isFinished = false;

		public bool isFinished
		{
			get { return m_isFinished; }
			set { m_isFinished = value; }
		}

		public PlayerHand hand
		{
			get { return m_hand; }
			set { m_hand = value; }
		}

		public Player (ePlayerType typeOfPlayer)
		{
			m_playerType = typeOfPlayer;
		}
	}
}

