//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CardGame
{
	public class Card
	{
		#region enums

		public enum eSuit	
		{ 	
			kNone = 0, 
			kClubs, kDiamonds, kHearts, kSpades
		};

		public enum eValue 
		{ 
				kNone	= 0
			,	kAce	= 1
			,	kTwo	= 2
			,	kThree
			,	kFour
			,	kFive
			,	kSix
			,	kSeven
			,	kEight
			,	kNine
			,	kTen
			,	kJack	= 11
			,	kQueen	= 12
			,	kKing	= 13
		};

		#endregion enums

		#region data_members

		protected eSuit m_Suit = eSuit.kNone;
		protected eValue m_Value = eValue.kNone;
		protected string m_name;

		#endregion data_members

		#region properties

		public eSuit Suit {  
			get { return m_Suit; }
			set {
				m_Suit = value;
			}

		}
		public eValue Value	
		{ 
			get { return m_Value; }
			set {
				m_Value = value;
			}
		}

		public string name { get { return m_name; } set { m_name = value; } }

		#endregion properties

		#region ctor
		public Card ()
		{

		}

		#endregion ctor

		#region methods



		#endregion methods

	}
}

