//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace CardGame
{
	public class Card
	{
		#region enums

		public enum eSuit	
		{ 	
			kNone = 0, 
			kClubs, kDiamonds, kHearts, kSpades
		};

		public enum eValue 
		{ 
				kNone	= 0
			,	kAce	= 1
			,	kTwo	= 2
			,	kThree
			,	kFour
			,	kFive
			,	kSix
			,	kSeven
			,	kEight
			,	kNine
			,	kTen
			,	kJack	= 11
			,	kQueen	= 12
			,	kKing	= 13
		};

		#endregion enums

		#region data_members

		protected eSuit m_Suit = eSuit.kNone;
		protected eValue m_Value = eValue.kNone;
		protected string m_name = "";

		#endregion data_members

		#region properties

		public eSuit Suit {  
			get { return m_Suit; }
			set 
			{
				m_Suit = value;
				m_name = GetName(m_Suit, m_Value);
			}

		}
		public eValue Value	
		{ 
			get { return m_Value; }
			set 
			{
				m_Value = value;
				m_name = GetName(m_Suit, m_Value);
			}
		}

		public string name 
		{ 
			get { return m_name; } 
		}

		#endregion properties

		#region ctor
		public Card ()
		{

		}

		public Card(eSuit suit, eValue val)
		{
			m_Suit = suit;
			m_Value = val;
			m_name = GetName(m_Suit, m_Value);
		}

		#endregion ctor

		#region methods

		public static string GetName(eSuit suit, eValue val)
		{
			string svalue = "";
			string ssuit = "";
			
			switch (val) {
			case Card.eValue.kAce:
				svalue += "ace";
				break;
			case Card.eValue.kTwo:
				svalue += "2";
				break;
			case Card.eValue.kThree:
				svalue += "3";
				break;
			case Card.eValue.kFour:
				svalue += "4";
				break;
			case Card.eValue.kFive:
				svalue += "5";
				break;
			case Card.eValue.kSix:
				svalue += "6";
				break;
			case Card.eValue.kSeven:
				svalue += "7";
				break;
			case Card.eValue.kEight:
				svalue += "8";
				break;
			case Card.eValue.kNine:
				svalue += "9";
				break;
			case Card.eValue.kTen:
				svalue += "10";
				break;
			case Card.eValue.kJack:
				svalue += "jack";
				break;
			case Card.eValue.kQueen:
				svalue += "queen";
				break;
			case Card.eValue.kKing:
				svalue += "king";
				break;
			default:
				return "";
			}
			
			switch (suit) {
			case Card.eSuit.kSpades:
				ssuit += "spades";
				break;
			case Card.eSuit.kHearts:
				ssuit += "hearts";
				break;
			case Card.eSuit.kDiamonds:
				ssuit += "diamonds";
				break;
			case Card.eSuit.kClubs:
				ssuit += "clubs";
				break;
			default:
				return "";
			}

			return svalue + " of " + ssuit;
		}

		#endregion methods

	}
}

