//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEditor;
using System.Collections;
using System.Collections.Generic;

namespace CardGame
{
	// Standard 52-card deck of playing cards

	public class StdDeck
	{
		List<Card> m_Deck = new List<Card>(52);

		public StdDeck ()
		{
			m_Deck.Capacity = 52;
		}

		public void Init()
		{
			ResetDeck();
			ShuffleDeck();
		}

		// add all cards
		public void ResetDeck()
		{
			m_Deck.RemoveRange(0, m_Deck.Count); // clear deck first
			for (uint iSuit = 1; iSuit <= 4; iSuit++)
			{
				for (uint iVal = 1; iVal <= 13; iVal++)
				{
					m_Deck.Add(new Card( (Card.eSuit)iSuit, (Card.eValue)iVal ));
					Debug.Log ("Added Card [" + m_Deck.Count + "]: " + m_Deck[m_Deck.Count-1].name);
				}
			}
		}

		public void ShuffleDeck()
		{
//			Random.seed = System.DateTime.Now.Millisecond;

			foreach (Card c in m_Deck)
			{
				m_Deck.Insert(Random.Range (0, m_Deck.Count), c);
			}
		}

		public Card DrawCard()
		{
			Card card = new Card(m_Deck[0].Suit, m_Deck[0].Value);
			m_Deck.RemoveAt(0);
			return card;
		}

		public bool empty()
		{
			return m_Deck.Count == 0;
		}

		public int size()
		{
			return m_Deck.Count;
		}
	}
}

